### ISSUE TITLE
Ripped code?

### ISSUE THREAD

**Issue by m0nad** [R3tr074/brokepkg#1]
This looks extremely similar to my rootkit https://github.com/m0nad/Diamorphine is that an impossible coincidence or just a ripped code? Please give the credits.

**Comment by m0nad** [comment]
Looks like another part of the code come from here https://xcellerator.github.io/posts/linux_rootkits_02/ @xcellerator

**Comment by xcellerator** [comment]
Hi, I did indeed come across your repo (among others) while I was researching different rootkit techniques.

As you can see on [this page](https://github.com/xcellerator/linux_kernel_hacking/blob/0b90f219d43dcbc1991be0e51b7452577a6b3cb8/3_RootkitTechniques/3.0_hiding_lkm/README.md) I added a link to your repo, giving credit for the inspiration. However, it was totally my mistake that in other relevant READMEs, I forgot to add it. I've now added them.

Regarding the second link you gave, that is my blog where I've written up detailed explanations of the different techniques in this repo.

Very sorry for the mistake!

**Comment by m0nad** [comment]
I didn't mean that you ripped @xcellerator, I mean that this repo here https://github.com/R3tr074/brokepkg/ (where this issue was created) ripped from me and your blog(BTW, great job there!).

Sorry for the misunderstanding, I should have explained better.

**Comment by xcellerator** [comment]
Haha, my bad, I guess I still need to wake up.
Definitely looks like some lifted code here. Even a readme shoutout would be nice

**Comment by magnologan** [comment]
Why is it so hard to give proper credits to the original creators? What do you win by doing that?

**Comment by m0nad** [comment]
Thanks for adding the references, @R3tr074. Closing the issue.
