### ISSUE TITLE
os hangs on insmod

### ISSUE THREAD

**Issue by xroot000** [R3tr074/brokepkg#2]
4.19.0-14-amd64 debian

**Comment by xroot000** [comment]
also os hangs on everything) you need more testing and debuggin')

**Comment by R3tr074** [comment]
Thanks for feedback and your suggest, but this kernel not crash in my tests, you can send my most informations for analizy?

One of my tests:
<img src="https://www.imagemhost.com.br/images/2021/04/17/mint.png" />
